services:
  openprofileserver:
    image: openprofileserver
    build:
      context: .
      dockerfile: OpenProfileServer/Dockerfile

  openprofileserver.generator:
    image: openprofileserver.generator
    build:
      context: .
      dockerfile: OpenProfileServer.Generator/Dockerfile

